# Generated by Django 4.1.3 on 2022-11-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "vin",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="VIN код",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                ("year_of_production", models.IntegerField(verbose_name="Рік випуску")),
                ("engine_volume", models.FloatField(verbose_name="Об'єм двигуна")),
                (
                    "wheel_drive",
                    models.CharField(
                        choices=[("1", "Повний"), ("2", "Передній"), ("3", "Задній")],
                        max_length=255,
                        verbose_name="Привід",
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[("0", "Бензин"), ("1", "Електро"), ("2", "Дизель")],
                        max_length=255,
                        verbose_name="Тип палива",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        choices=[
                            ("0", "Седан"),
                            ("1", "Кросовер"),
                            ("2", "Мінівен"),
                            ("3", "Мікровен"),
                            ("4", "Хетчбек"),
                            ("5", "Універсал"),
                            ("6", "Купе"),
                            ("7", "Кабріолет"),
                            ("8", "Пікап"),
                            ("9", "Ліфтбек"),
                            ("10", "Фастбек"),
                            ("11", "Лімузин"),
                            ("12", "Родстер"),
                        ],
                        max_length=255,
                        verbose_name="Тип кузова",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобіль",
                "verbose_name_plural": "Автомобілі",
            },
        ),
        migrations.CreateModel(
            name="CarProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
            ],
            options={
                "verbose_name": "Виробник",
                "verbose_name_plural": "Виробники",
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                ("amount", models.IntegerField(blank=True, verbose_name="Кількість")),
                (
                    "belongs_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.auto",
                        verbose_name="Автомобіль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запчастина",
                "verbose_name_plural": "Запчастини",
            },
        ),
        migrations.AddField(
            model_name="auto",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.carproducer",
                verbose_name="Виробник",
            ),
        ),
    ]
