# Generated by Django 4.1 on 2022-11-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                ("year_of_production", models.IntegerField(verbose_name="Рік випуску")),
            ],
        ),
        migrations.CreateModel(
            name="CarProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                ("amount", models.IntegerField(verbose_name="Кількість")),
                (
                    "belongs_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="main.auto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auto",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.carproducer"
            ),
        ),
    ]
