# Generated by Django 4.1.3 on 2022-11-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AlterModelOptions(
            name='carproducer',
            options={'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Запчастина', 'verbose_name_plural': 'Запчастини'},
        ),
        migrations.RemoveField(
            model_name='auto',
            name='id',
        ),
        migrations.AddField(
            model_name='auto',
            name='engine_volume',
            field=models.FloatField(default=0, verbose_name="Об'єм двигуна"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 0), ('Електро', 1), ('Дизель', 2)], default=1, max_length=255, verbose_name='Тип палива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='vin',
            field=models.CharField(default=(0, 1, 2, 3), max_length=64, primary_key=True, serialize=False, verbose_name='VIN код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='wheel_drive',
            field=models.CharField(choices=[('Повний', '1'), ('Передній', '2'), ('Задній', '3')], default='1', max_length=255, verbose_name='Привід'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carproducer', verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='part',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='part',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.auto', verbose_name='Автомобіль'),
        ),
    ]
