# Generated by Django 4.1.3 on 2022-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="amount",
        ),
        migrations.AddField(
            model_name="part",
            name="articul",
            field=models.CharField(blank=True, max_length=255, verbose_name="Артикул"),
        ),
        migrations.AddField(
            model_name="part",
            name="buy_price",
            field=models.FloatField(
                blank=True, default=0, verbose_name="Закупочна ціна"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="sell_price",
            field=models.FloatField(
                blank=True, default=0, verbose_name="Роздрібна ціна"
            ),
            preserve_default=False,
        ),
    ]
